"""empty message

Revision ID: b25fae3aaf8c
Revises: 68bb421733e5
Create Date: 2023-05-16 11:46:52.866904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b25fae3aaf8c'
down_revision = '68bb421733e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.drop_column('location')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('location')

    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.VARCHAR(length=50), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
